version: "3"

services:

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - DATABASE_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/db:/var/lib/postgresql/data

  back:
    container_name: back
    build: ./back
    ports:
      - "5000:5000"
    links:
      - postgres


  client:
    container_name: client
    build: ./front
    ports:
      - "443:443"
    links:
      - back
